name: Kotlin CI

on:
  push:
    paths:
      - "app_kotlin/**"
  pull_request:
    paths:
      - "app_kotlin/**"
  workflow_dispatch:

jobs:
  buildlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make Gradle executable
        working-directory: ./app_kotlin
        run: chmod +x ./gradlew

      - name: Build project
        working-directory: ./app_kotlin
        run: ./gradlew build

      - name: Check lint
        uses: vroy/gha-kotlin-linter@v1
        with: {}

  docker:
    needs: buildlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/app_kotlin:latest ./app_kotlin

      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app_kotlin:latest

  snyk:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make Gradle executable
        working-directory: ./app_kotlin
        run: chmod +x ./gradlew

      - name: Run Snyk
        uses: snyk/actions/gradle-jdk21@master
        with:
          args: test ./app_kotlin --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
